import '@shopify/ui-extensions';

// @ts-expect-error — auto-generated by `shopify app dev`; the import-module
// form below doesn't match a resolvable type, but Shopify's runtime wires up
// `globalThis.shopify` inside the extension sandbox.
declare module './src/BlockExtension.jsx' {
  const shopify: import('@shopify/ui-extensions/admin.order-details.block.render').Api;
  const globalThis: { shopify: typeof shopify };
}
