# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be6ffd8b113b73476546c4cefdccc3fb"
name = "promo-guard"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"
  include_fields = [
  "id",
  "admin_graphql_api_id",
  "name",
  "created_at",
  "updated_at",
  "email",
  "phone",
  "customer",
  "discount_codes",
  "discount_applications",
  "shipping_address",
  "billing_address",
  "browser_ip",
  "client_details",
  "total_price",
  "currency"
]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_products,write_customers,write_discounts,write_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
